
# Search for suggested NS to backup
tvk_suggest: true
# Auto create NS Backup Plan 
tvk_autoprotect: true
# List of NS to exclude
tvk_autoprotect_exclude: ['openshift-storage', 'openshift-operators']

# app yaml to deploy
tvk_deploy_demo_app: false
tvk_namespace: shailesh-label-backup

#
# Backup Target
#
# Currently assumes AWS S3
# IMPORTANT: See templates/target.yaml.j2 to modify for other targets
# TODO: Specify NFS or S3
tvk_create_target: true
tvk_target_type: S3
tvk_target_name: vm-backup-target
tvk_s3_bucket_name: tvk-migration-demo1
tvk_secret_name: s3-access-secret

#
# Backup Plan Details
# Note this must be relevant to the test/demo app
#
tvk_create_backupplan: true
tvk_backupplan_name: vm-backupplan
tvk_backupplan_type: ns # ns|label
tvk_backup_match_label: "app: k8s-demo-app" # ignored for ns backup type

#
# Perform Backup
tvk_backup_prefix: "{{ tvk_backupplan_name }}"
tvk_backup_type: Full # Full | Incremental
