---
# This set of playbooks will perform a smoketest of TVK 
#
# - check for kubectl and oc (if openshift)
# - create the demo app in the namespace specified in /vagrant/tvk-config.yaml
# - create a target as specified in the tvk-config.yaml
# - create a backupplan as specified
# - perform a backup
# - restore application to a newly created ns
#
#

###### CONFIGURATION #######
# See tvk-config.yaml
############################
#

- name: Trilio for Kubernetes Smoketest
  hosts: localhost
  vars_files:
    tvk-config.yaml
  roles:
  - trilio-kubernetes
  vars:
    tvk_smoketest: true