---
# This playbook will create the demo app in the namespace specified in /vagrant/config.yaml

- name: Create Demo Applications
  hosts: localhost
  vars_files:
    tvk-config.yaml
  roles:
  - create-demo-app

- name: Create Demo Application
  hosts: localhost
  vars_files:
    tvk-config.yaml
  roles:
    - trilio-kubernetes
  vars:
    tvk_deploy_demo_app: true