# - name: Trilio for Kubernetes Smoketest
#  ansible.builtin.include_tasks: tvk_smoketest.yaml
#  when: tvk_smoketest | bool
#  tags: ['smoketest']

- name: Authentication to Kubernetes
  ansible.builtin.include_tasks: tvk_auth.yaml
  when: tvk_auth | bool
  tags: ['always', 'auth']

- name: Basic Trilio for Kubernetes Checks
  ansible.builtin.include_tasks: tvk_check.yaml
  when: tvk_check | bool
  tags: ['check', 'smoketest']

- name: Searching for Backup Recommendations
  ansible.builtin.include_tasks: tvk_suggest.yaml
  when: tvk_suggest | bool
  tags: ['suggest', 'search', 'autoprotect', 'smoketest']

- name: Trilio for Kubernetes Deploy App
  ansible.builtin.include_tasks: tvk_deploy_app.yaml
  when: tvk_deploy_demo_app | bool
  tags: ['deploy_app', 'smoketest']

- name: Trilio for Kubernetes Create Target
  ansible.builtin.include_tasks: tvk_create_target.yaml
  when: tvk_create_target | bool
  tags: ['target', 'smoketest']

- name: Trilio for Kubernetes Create Backup Plan
  ansible.builtin.include_tasks: tvk_create_backupplan.yaml
  when: tvk_create_target | bool
  tags: ['backupplan', 'smoketest']

- name: Trilio for Kubernetes Execute a Backup
  ansible.builtin.include_tasks: tvk_create_backup.yaml
  when: tvk_create_target | bool
  tags: ['backup', 'smoketest']

- name: Cleanup Trilio For Kubernetes Test
  ansible.builtin.include_tasks: tvk_cleanup.yaml
  when: tvk_cleanup | bool
  tags: ['never', 'cleanup', 'smoketest']
