- name: Create {{ tvk_namespace }} namespace
  kubernetes.core.k8s:
    name: "{{ tvk_namespace }}" # defining the namespace
    api_version: v1
    api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    kind: Namespace
    validate_certs: false
    state: present # State=present when you need to create new object
  when: k8s_auth_type == 'password'
  tags: ['namespace', 'ns', 'smoketest', 'target', 'deploy_app', 'backupplan']

# For OpenShift we need to ensure the correct SCC is allowed
# Hack: ensure SCC is set, assumes kubeadmin username
- name: Set SCC Policy for {{ tvk_namespace }} namespace for OpenShift deployments
  shell: |
    oc login "{{ k8s_auth_api }}" --token="{{ openshift_auth_results.openshift_auth.api_key }}" --insecure-skip-tls-verify=true
    oc adm policy add-scc-to-user anyuid -z default -n "{{ tvk_namespace }}"
  register: scc
  when:
  - k8s_auth_type == "password"
  - k8s_distro == "openshift"
  - k8s_username == "kubeadmin"
  - tvk_scc_policy_anyuid_to_ns | bool
  tags: ['namespace', 'deploy_app', 'smoketest']
