# Set of tasks that will authenticate to OpenShift
# User can use kubeconfig or user/pass
# If a user is authenticating using username/password:
# Create an encrypted vault file with the following format
# k8s_username:
# k8s_password:
# Pass this encrypted vault file on the ansible command line
#
# Authors: Kevin Jackson <kevin.jackson at trilio io>


- name: Kubernetes Authentication
  block:
  - name: Check Kubeconfig is available
    stat:
      path: "{{ kubeconfig }}"
    when: k8s_auth_type == 'kubeconfig'
  tags: ['always', 'auth', 'smoketest', 'migrate']
