# Set of tasks that will authenticate to OpenShift
# User can use kubeconfig or user/pass
# If a user is authenticating using username/password:
# Create an encrypted vault file with the following format
# k8s_username:
# k8s_password:
# Pass this encrypted vault file on the ansible command line
#
# Authors: Kevin Jackson <kevin.jackson at trilio io>


- name: Kubernetes Authentication
  block:
  - name: Configure Authentication
    ansible.builtin.set_fact: username="{{ k8s_username }}" password="{{ k8s_password }}" host="{{ k8s_auth_api }}"
    when:
    - k8s_auth_type == 'password'

  - name: Log in to OpenShift (obtain access token)
    community.okd.openshift_auth:
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: false
      host: "{{ host }}"
    register: openshift_auth_results
    when:
    - k8s_distro == 'openshift'
    - k8s_auth_type == 'password'

  - name: Auth Fact Set
    set_fact: k8s_auth_results="{{ openshift_auth_results }}"
    when:
    - k8s_distro == 'openshift'
    - k8s_auth_type == 'password'
  tags: ['always', 'auth', 'smoketest', 'migrate']
