# Set of tasks for creating a Trilio for Kubernetes Backup Plan in a namespace
# for describing what and where to backup
#
# Authors: Kevin Jackson <kevin.jackson at trilio io>

- name: Create Backup Plan
  block:
  - name: Configure backup plan in {{ tvk_namespace }}
    template:
      src: templates/{{ tvk_backupplan_name }}-backupplan.yaml.j2
      dest: /tmp/{{ tvk_backupplan_name }}-backupplan.yaml

  # Create the specified backup plan in specifed namespace
  - name: Create the "{{ tvk_backupplan_name }}" backup plan in {{ tvk_namespace }} namespace
    kubernetes.core.k8s:
      state: present # State=present when you need to create new object
      namespace: "{{ tvk_namespace }}" # defining the namespace
      src: "/tmp/{{ tvk_backupplan_name }}-backupplan.yaml"
      validate_certs: false
    register: backupplan

  # TODO: if not using kubeconfig auth, how to do kubectl?
  - name: Wait for "{{ tvk_backupplan_name }}" backup plan of type {{ tvk_backup_type }} in {{ tvk_namespace }} namespace (kubeconfig)
    shell: >
      kubectl get backupplans/"{{ tvk_backupplan_name }}" -n {{ tvk_namespace }}
    environment:
      KUBECONFIG: "{{ kubeconfig }}"
    register: backupplan_available
    retries: 5
    delay: 5
    until: backupplan_available.stdout.find("Available") != -1
    ignore_errors: true
    when:
    - kube_auth_type == "kubeconfig"

  - name: Wait for "{{ tvk_backupplan_name }}" backup plan in {{ tvk_namespace }} namespace (token)
    shell: |
      oc login "{{ kube_auth_api }} " --token="{{ openshift_auth_results.openshift_auth.api_key }}" --insecure-skip-tls-verify=true
      oc get backupplans/"{{ tvk_backupplan_name }}" -n {{ tvk_namespace }}
    register: backupplan_available
    retries: 5
    delay: 10
    until: backupplan_available.stdout.find("Available") != -1
    ignore_errors: true
    when:
    - kube_auth_type == "password"
    - kube_distro == "openshift"
  - debug: var=backupplan_available.stdout_lines
  tags: ['backupplan', 'smoketest', 'autoprotect']

