# Set of tasks for creating a Trilio for Kubernetes Backup Plan in a namespace
# for describing what and where to backup
#
# Authors: Kevin Jackson <kevin.jackson at trilio io>

- name: Create Backup Plan
  block:
  - name: Configure backup plan in {{ tvk_namespace }}
    template:
      src: templates/backupplan.yaml.j2
      dest: /tmp/"{{ tvk_namespace }}"-backupplan.yaml
  tags: ['search', 'autoprotect']
