# Set of tasks for creating a secret in a namespace
# for storing S3 based backups when auth is password
#
# Authors: Kevin Jackson <kevin.jackson at trilio io>

- name: Create Secret for S3
  block:
  # Create a secret using file stored locally
  - name: Configure the secret yaml
    template:
      src: templates/secrets.yaml.j2
      dest: /tmp/secrets.yaml
      mode: 0600
    register: k8s_secret

  - name: Create the secret used by the S3 target in the {{ tvk_namespace }} namespace
    kubernetes.core.k8s:
      api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
      kind: Secret
      state: present # State=present when you need to create new object
      namespace: "{{ tvk_namespace }}" # namespace for the secret
      validate_certs: false
      src: /tmp/secrets.yaml
    register: secret
    when: k8s_auth_type == 'password'

  - name: Remove temporary secret yaml
    ansible.builtin.file:
      path: /tmp/secrets.yaml
      state: absent
    when: tvk_target_type | lower == "s3"
  tags: ['target', 'secret', 'smoketest']
