# Set of tasks for creating a Trilio for Kubernetes Backup Plan in a namespace
# for describing what and where to backup
#
# Authors: Kevin Jackson <kevin.jackson at trilio io>

- name: Create Backup Plan Tasks
  block:
  - name: Configure the backup plan in {{ tvk_namespace }}
    template:
      src: templates/backupplan.yaml.j2
      dest: /tmp/{{ tvk_backupplan_name }}-backupplan.yaml

  # Create the specified backup plan in specifed namespace
  - name: Create the "{{ tvk_backupplan_name }}" backup plan in {{ tvk_namespace }} namespace
    kubernetes.core.k8s:
      api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
      kind: BackupPlan
      state: present # State=present when you need to create new object
      namespace: "{{ tvk_namespace }}" # defining the namespace
      src: "/tmp/{{ tvk_backupplan_name }}-backupplan.yaml"
      validate_certs: false
    register: backupplan
    when: k8s_auth_type == "password"

  - name: Wait for the "{{ tvk_backupplan_name }}" backup plan to be created in {{ tvk_namespace }} namespace
    shell: |
      oc login "{{ k8s_auth_api }}" --token="{{ openshift_auth_results.openshift_auth.api_key }}" --insecure-skip-tls-verify=true 2>&/dev/null
      oc get backupplans/"{{ tvk_backupplan_name }}" -n {{ tvk_namespace }}
    register: backupplan_available
    retries: 5
    delay: 10
    until: backupplan_available.stdout.find("Available") != -1
    ignore_errors: true
    when:
    - k8s_auth_type == "password"
    - k8s_distro == "openshift"
  - debug: var=backupplan_available.stdout_lines
  tags: ['backup', 'backupplan', 'smoketest', 'autoprotect']
