---
# This playbook will create the target in the namespace specified in /vagrant/config.yaml

- name: Create Backup Target
  hosts: localhost
  vars_files:
    tvk-config.yaml
  roles:
    - create-target
  vars:
    tvk_create_target: true
